// web/src/core/contest-view.tsx
import { gql } from '@apollo/client';
import { css } from 'emotion';
import React from 'react';
import { ContestViewFragment } from '../generated/graphql-types';
import { hiddenCss } from '../util/components/hidden';
import { FragmentProps } from '../util/fragment-props';
import { PathRouter } from '../util/paths';
import {
  ContestProblemAssignmentViewAside,
  contestProblemAssignmentViewAsideFragment,
} from './contest-problem-assignment-view-aside';
import { ContestViewAside, contestViewAsideFragment } from './contest-view-aside';
import { MediaInline, mediaInlineFragment } from './media-inline';
import { textFragment } from './text';

export const contestViewFragment = gql`
  fragment ContestView on ContestView {
    contest {
      id
      title {
        ...Text
      }
      statement {
        ...MediaInline
      }
    }

    problemSetView {
      assignmentViews {
        assignment {
          id
          problem {
            id
            name
            statement {
              ...MediaInline
            }
          }
        }
        ...ContestProblemAssignmentViewAside
      }
    }

    ...ContestViewAside
  }

  ${textFragment}
  ${mediaInlineFragment}
  ${contestViewAsideFragment}
  ${contestProblemAssignmentViewAsideFragment}
`;

const activeMediaInlineCss = css`
  flex: 1;
  overflow: hidden;
`;

export function ContestView({ data }: FragmentProps<ContestViewFragment>) {
  return (
    <div
      className={css`
        flex: 1 1 0;

        display: flex;
        flex-direction: row;
        overflow: hidden;
      `}
    >
      <ContestViewAside data={data} />
      {data.problemSetView !== null &&
        data.problemSetView.assignmentViews.map(a => (
          <PathRouter key={a.assignment.problem.id} path={`/${a.assignment.problem.name}`}>
            {({ match }) => (
              <>
                <ContestProblemAssignmentViewAside className={match !== null ? undefined : hiddenCss} data={a} />
                <div className={match !== null ? activeMediaInlineCss : hiddenCss}>
                  <MediaInline data={a.assignment.problem.statement} />
                </div>
              </>
            )}
          </PathRouter>
        ))}
      <PathRouter path="/" exact>
        {({ match }) => (
          <div className={match !== null ? activeMediaInlineCss : hiddenCss}>
            <MediaInline data={data.contest.statement} />
          </div>
        )}
      </PathRouter>
    </div>
  );
}

// web/src/core/contest-view.component.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import gql from 'graphql-tag';
import { ContestViewFragment } from '../generated/graphql-types';
import { contestProblemAssignmentViewAsideFragment } from './contest-problem-assignment-view-aside.component';
import { contestViewAsideFragment } from './contest-view-aside.component';
import { mediaInlineFragment } from './material/media-inline.component';
import { textFragment } from './material/text.pipe';

@Component({
  selector: 'app-contest-view',
  templateUrl: './contest-view.component.html',
  styleUrls: ['./contest-view.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class ContestViewComponent {
  @Input()
  data!: ContestViewFragment;

  constructor(readonly route: ActivatedRoute) {}
}

export const contestViewFragment = gql`
  fragment ContestView on ContestView {
    contest {
      id
      title {
        ...Text
      }
      statement {
        ...MediaInline
      }
    }

    problemSetView {
      assignmentViews {
        assignment {
          id
          problem {
            id
            name
            statement {
              ...MediaInline
            }
          }
        }
        ...ContestProblemAssignmentViewAside
      }
    }

    ...ContestViewAside
  }

  ${textFragment}
  ${mediaInlineFragment}
  ${contestViewAsideFragment}
  ${contestProblemAssignmentViewAsideFragment}
`;

<app-contest-view-aside [data]="data"></app-contest-view-aside>

<ng-container *ngIf="data.problemSetView! as problemSetView">
  <ng-container *ngFor="let assignmentView of problemSetView.assignmentViews">
    <app-contest-problem-assignment-view-aside
      [hidden]="(route.firstChild!.paramMap | async)?.get('problemName') !== assignmentView.assignment.problem.name"
      [data]="assignmentView"></app-contest-problem-assignment-view-aside>
  </ng-container>
</ng-container>

<app-media-inline [hidden]="(route.firstChild!.paramMap | async)?.has('problemName')" [data]="data.contest.statement">
</app-media-inline>

<ng-container *ngIf="data.problemSetView! as problemSetView">
  <ng-container *ngFor="let assignmentView of problemSetView.assignmentViews">
    <app-media-inline
      [hidden]="(route.firstChild!.paramMap | async)?.get('problemName') !== assignmentView.assignment.problem.name"
      [data]="assignmentView.assignment.problem.statement"></app-media-inline>
  </ng-container>
</ng-container>
