// web/src/core/contest-problem-assignment-view-aside.component.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';
import gql from 'graphql-tag';
import { ContestProblemAssignmentViewAsideFragment } from '../generated/graphql-types';
import { contestProblemAssignmentUserTacklingAsideFragment } from './contest-problem-assignment-user-tackling-aside.component';
import { gradeFieldFragment } from './grading/grade-field.component';
import { scoreFieldFragment } from './grading/score-field.component';
import { mediaDownloadFragment } from './material/media-download.component';
import { mediaInlineFragment } from './material/media-inline.component';
import { textFragment } from './material/text.pipe';

@Component({
  selector: 'app-contest-problem-assignment-view-aside',
  templateUrl: './contest-problem-assignment-view-aside.component.html',
  styleUrls: ['./contest-problem-assignment-view-aside.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class ContestProblemAssignmentViewAsideComponent {
  @Input()
  data!: ContestProblemAssignmentViewAsideFragment;
}

export const contestProblemAssignmentViewAsideFragment = gql`
  fragment ContestProblemAssignmentViewAside on ContestProblemAssignmentView {
    assignment {
      id
      problem {
        id
        name
        title {
          ...Text
        }
        statement {
          ...MediaInline
          ...MediaDownload
        }
        attachments {
          title {
            ...Text
          }
          media {
            ...MediaDownload
          }
        }
      }
    }

    totalScoreField {
      ...ScoreField
    }

    awardAssignmentViews {
      assignment {
        id
        award {
          id
          name
          title {
            ...Text
          }
        }
      }

      gradeField {
        ...GradeField
      }
    }

    tackling {
      ...ContestProblemAssignmentUserTacklingAside
    }
  }

  ${textFragment}
  ${mediaInlineFragment}
  ${mediaDownloadFragment}
  ${scoreFieldFragment}
  ${gradeFieldFragment}
  ${contestProblemAssignmentUserTacklingAsideFragment}
`;

<div class="problem-submission-panel">
  <ng-container *ngIf="data.canSubmit">
    <button class="problem-submit" (click)="modalService.open(submitDialog)">
      <fa-icon icon="paper-plane"></fa-icon>
      Submit a solution
      <ng-template #submitDialog let-modal>
        <app-contest-problem-assignment-view-submit-modal [data]="data" [modal]="modal"></app-contest-problem-assignment-view-submit-modal>
      </ng-template>
    </button>
  </ng-container>

  <ng-container *ngIf="data.submissions[data.submissions.length - 1] as lastSubmission">
    <button class="problem-last-submission" (click)="modalService.open(lastSubmissionDialog, { size: 'lg' })">
      <fa-icon *ngIf="lastSubmission.evaluation.status !== 'PENDING'" icon="history"> </fa-icon>
      <fa-icon *ngIf="lastSubmission.evaluation.status === 'PENDING'" icon="spinner" [pulse]="true">
      </fa-icon>
      Last submission
    </button>

    <button class="problem-submission-list" (click)="modalService.open(submissionListDialog, { size: 'xl' })">
      <fa-icon icon="list"></fa-icon>
      All submissions
    </button>
  </ng-container>
</div>
<div class="problem-info">
  <ng-container *ngIf="data.awardAssignmentViews.length > 0">
    <h3 class="problem-award-list-title">Awards</h3>
    <div class="problem-award-list">
      <ng-container *ngFor="let awardAssignmentView of data.awardAssignmentViews">
        <div class="problem-award" [title]="awardAssignmentView.assignment.award.title | text">
          {{ awardAssignmentView.assignment.award.title | text }}
          <span class="problem-award-grading" [appValence]="awardAssignmentView.gradingState">
            <app-grading [data]="awardAssignmentView.gradingState"></app-grading>
          </span>
        </div>
      </ng-container>
    </div>
  </ng-container>
  <ng-container *ngIf="data.assignment.problem.attachments.length > 0">
    <h3 class="problem-attachment-list-title">Attachments</h3>
    <div class="problem-attachment-list">
      <ng-container *ngFor="let attachment of data.assignment.problem.attachments">
        <app-media-download [data]="attachment.media"></app-media-download>
      </ng-container>
    </div>
  </ng-container>
  <h2 class="problem-download-statement-title">Statement file</h2>
  <app-media-download class="problem-download-statement" [data]="data.assignment.problem.statement"></app-media-download>
</div>

// web/src/core/contest-problem-assignment-view-aside.tsx
import { gql } from '@apollo/client';
import { css, cx } from 'emotion';
import React, { HTMLAttributes } from 'react';
import { ContestProblemAssignmentViewAsideFragment } from '../generated/graphql-types';
import { badgeCss, getBadgeCssByValence } from '../util/components/badge';
import { FragmentProps } from '../util/fragment-props';
import {
  ContestProblemAssignmentUserTacklingAside,
  contestProblemAssignmentUserTacklingAsideFragment,
} from './contest-problem-assignment-user-tackling-aside';
import { GradeField, gradeFieldFragment, scoreFieldFragment } from './fields/grade-field';
import { MediaDownload, mediaDownloadFragment } from './media-download';
import { mediaInlineFragment } from './media-inline';
import { textFragment } from './text';

export const contestProblemAssignmentViewAsideFragment = gql`
  fragment ContestProblemAssignmentViewAside on ContestProblemAssignmentView {
    assignment {
      id
      problem {
        id
        name
        title {
          ...Text
        }
        statement {
          ...MediaInline
          ...MediaDownload
        }
        attachments {
          title {
            ...Text
          }
          media {
            ...MediaDownload
          }
        }
      }
    }

    totalScoreField {
      ...ScoreField
    }

    awardAssignmentViews {
      assignment {
        id
        award {
          id
          name
          title {
            ...Text
          }
        }
      }

      gradeField {
        ...GradeField
      }
    }

    tackling {
      ...ContestProblemAssignmentUserTacklingAside
    }
  }

  ${textFragment}
  ${mediaInlineFragment}
  ${mediaDownloadFragment}
  ${scoreFieldFragment}
  ${gradeFieldFragment}
  ${contestProblemAssignmentUserTacklingAsideFragment}
`;

const asideTitleCss = css`
  text-transform: uppercase;
  font-size: 1.125rem;
  margin: 0 0 0.5rem;
  font-weight: 500;
  line-height: 1.2;
`;

const downloadLinkCss = css`
  display: block;
  color: inherit;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;

  &:hover {
    text-decoration: none;
  }
`;

export function ContestProblemAssignmentViewAside({
  data,
  className,
  ...rest
}: FragmentProps<ContestProblemAssignmentViewAsideFragment> & HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      className={cx(
        className,
        css`
          flex: 0 0 auto;
          width: 15em;
          background-color: #f8f9fa;
        `,
      )}
      {...rest}
    >
      {data.tackling !== null && <ContestProblemAssignmentUserTacklingAside data={data.tackling} />}
      <div
        className={css`
          padding: 16px;
          flex: 1 1 100%;
          overflow-y: auto;
        `}
      >
        {data.awardAssignmentViews.length > 0 && (
          <>
            <h3 className={asideTitleCss}>Awards</h3>
            <div
              className={css`
                padding: 0;
                list-style: none;

                margin-bottom: 16px;
              `}
            >
              {data.awardAssignmentViews.map((v, i) => (
                <div
                  key={i}
                  className={css`
                    margin: 0 -16px;
                    padding: 0 16px;

                    overflow: hidden;

                    display: flex;
                    flex-direction: row;

                    &:nth-of-type(odd) {
                      background-color: rgba(0, 0, 0, 0.05);
                    }

                    &:nth-of-type(even) {
                      background-color: rgba(0, 0, 0, 0.02);
                    }
                  `}
                  title={v.assignment.award.title.variant}
                >
                  <span
                    className={css`
                      overflow: hidden;
                      text-overflow: ellipsis;
                      white-space: nowrap;
                    `}
                  >
                    {v.assignment.award.title.variant}
                  </span>
                  <span
                    className={cx(
                      css`
                        margin-left: auto;
                      `,
                      badgeCss,
                      getBadgeCssByValence(v.gradeField?.valence ?? null),
                    )}
                  >
                    <GradeField data={v.gradeField} />
                  </span>
                </div>
              ))}
            </div>
          </>
        )}
        {data.assignment.problem.attachments.length > 0 && (
          <>
            <h3 className={asideTitleCss}>Attachments</h3>
            <div
              className={css`
                margin-bottom: 16px;
              `}
            >
              {data.assignment.problem.attachments.map((a, i) => (
                <MediaDownload key={i} className={downloadLinkCss} data={a.media} />
              ))}
            </div>
          </>
        )}
        <h2 className={asideTitleCss}>Statement file</h2>
        <MediaDownload className={downloadLinkCss} data={data.assignment.problem.statement} />
      </div>
    </div>
  );
}
