// web/src/core/contest-problem-assignment-user-tackling-submission-list.component.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';
import { ColDef } from 'ag-grid-community';
import gql from 'graphql-tag';
import { DateTime } from 'luxon';
import {
  ContestProblemAssignmentUserTacklingSubmissionListFragment,
  ContestProblemAssignmentUserTacklingSubmissionListSubmissionFragment,
} from '../generated/graphql-types';
import { getFieldColumns } from './data/field-table';
import { textFragment } from './material/text.pipe';
import { submissionModalFragment } from './submission-modal.component';

@Component({
  selector: 'app-contest-problem-assignment-user-tackling-submission-list',
  templateUrl: './contest-problem-assignment-user-tackling-submission-list.component.html',
  styleUrls: ['./contest-problem-assignment-user-tackling-submission-list.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class ContestProblemAssignmentUserTacklingSubmissionListComponent {
  constructor(readonly modalService: NgbModal) {}

  @Input()
  data!: ContestProblemAssignmentUserTacklingSubmissionListFragment;

  openSubmission!: ContestProblemAssignmentUserTacklingSubmissionListSubmissionFragment;

  getSummaryRows(submissions: ContestProblemAssignmentUserTacklingSubmissionListSubmissionFragment[]) {
    return submissions.map(s => s.summaryRow);
  }

  getColumns(data: ContestProblemAssignmentUserTacklingSubmissionListFragment): ColDef[] {
    return [
      {
        colId: 'time',
        headerName: 'Submitted at',
        sortable: true,
        sort: 'desc',
        sortingOrder: ['desc', 'asc', null] as string[],
        valueGetter: ({ data: submission }) =>
          (submission as ContestProblemAssignmentUserTacklingSubmissionListSubmissionFragment).createdAt.local,
        valueFormatter: ({ value: dateString }) =>
          DateTime.fromISO(dateString as string).toRelative() ?? `${dateString}`,
        tooltipValueGetter: ({ value: dateString }) => `${dateString}`.replace('T', ' '),
      },
      ...getFieldColumns(
        data.assignmentView.assignment.problem.submissionListColumns,
        (submission: ContestProblemAssignmentUserTacklingSubmissionListSubmissionFragment) => submission.summaryRow,
      ),
    ];
  }
}

export const contestProblemAssignmentUserTacklingSubmissionListFragment = gql`
  fragment ContestProblemAssignmentUserTacklingSubmissionList on ContestProblemAssignmentUserTackling {
    submissions {
      ...ContestProblemAssignmentUserTacklingSubmissionListSubmission
    }

    assignmentView {
      assignment {
        problem {
          submissionListColumns {
            ...Column
          }
        }
      }
    }
  }

  fragment ContestProblemAssignmentUserTacklingSubmissionListSubmission on Submission {
    id
    createdAt {
      local
    }
    # TODO: submission files
    officialEvaluation {
      status
    }
    summaryRow {
      ...Record
    }

    feedbackTable {
      columns {
        ...Column
      }
      rows {
        ...Record
      }
    }

    ...SubmissionModal
  }

  ${submissionModalFragment}
  ${textFragment}
`;

<ag-grid-angular class="ag-theme-balham" domLayout="autoHeight" [rowData]="data.submissions"
  [columnDefs]="data | applyPure: getColumns" (gridSizeChanged)="$event.api.sizeColumnsToFit()"
  (rowClicked)="openSubmission = $event.node.data; modalService.open(submissionModal, { size: 'lg' })"
  rowClass="submission-row"
  >
</ag-grid-angular>

<ng-template #submissionModal let-modal>
  <app-submission-modal [modal]="modal" [id]="openSubmission.id">
  </app-submission-modal>
</ng-template>

// web/src/core/contest-problem-assignment-user-tackling-submission-list.tsx
import { gql } from '@apollo/client';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { ColDef } from 'ag-grid-community';
import { AgGridReact } from 'ag-grid-react';
import { css } from 'emotion';
import { DateTime } from 'luxon';
import React from 'react';
import { Link } from 'react-router-dom';
import {
  ContestProblemAssignmentUserTacklingSubmissionListFragment,
  ContestProblemAssignmentUserTacklingSubmissionListSubmissionFragment,
} from '../generated/graphql-types';
import { FragmentProps } from '../util/fragment-props';
import { useBasePath } from '../util/paths';
import { columnFragment, getFieldColumns, recordFragment } from './field-table';
import { textFragment } from './text';

export const contestProblemAssignmentUserTacklingSubmissionListFragment = gql`
  fragment ContestProblemAssignmentUserTacklingSubmissionList on ContestProblemAssignmentUserTackling {
    submissions {
      ...ContestProblemAssignmentUserTacklingSubmissionListSubmission
    }

    assignmentView {
      assignment {
        problem {
          submissionListColumns {
            ...Column
          }
        }
      }
    }
  }

  fragment ContestProblemAssignmentUserTacklingSubmissionListSubmission on Submission {
    id
    createdAt {
      local
    }
    # TODO: submission files
    officialEvaluation {
      status
    }
    summaryRow {
      ...Record
    }

    feedbackTable {
      columns {
        ...Column
      }
      rows {
        ...Record
      }
    }
  }

  ${textFragment}
  ${columnFragment}
  ${recordFragment}
`;

export function ContestProblemAssignmentUserTacklingSubmissionList({
  data,
}: FragmentProps<ContestProblemAssignmentUserTacklingSubmissionListFragment>) {
  const basePath = useBasePath();

  const columns: ColDef[] = [
    {
      colId: 'time',
      headerName: 'Submitted at',
      sortable: true,
      sort: 'desc',
      sortingOrder: ['desc', 'asc', null] as string[],
      flex: 1,
      valueGetter: ({
        data: submission,
      }: {
        data: ContestProblemAssignmentUserTacklingSubmissionListSubmissionFragment;
      }) => submission.createdAt.local,
      tooltipValueGetter: ({ value: dateString }: { value?: string }) => `${dateString ?? ''}`.replace('T', ' '),
      cellRendererFramework: ({
        data: submission,
      }: {
        data: ContestProblemAssignmentUserTacklingSubmissionListSubmissionFragment;
      }) => (
        <Link
          className={css`
            display: flex;
          `}
          to={`${basePath}/submission/${submission.id}`}
        >
          {DateTime.fromISO(submission.createdAt.local).toRelative() ?? `${submission.createdAt.local}`}
          {submission.officialEvaluation?.status === 'PENDING' && (
            <span
              className={css`
                margin-left: auto;
              `}
            >
              <FontAwesomeIcon icon="spinner" pulse />
            </span>
          )}
        </Link>
      ),
    },
    ...getFieldColumns(
      data.assignmentView.assignment.problem.submissionListColumns,
      (submission: ContestProblemAssignmentUserTacklingSubmissionListSubmissionFragment) => submission.summaryRow,
    ),
  ];

  const rowData = JSON.parse(JSON.stringify(data.submissions)) as typeof data.submissions; // allow AgGrid to mess with this data

  return <AgGridReact domLayout="autoHeight" columnDefs={columns} rowData={rowData} />;
}
