// web/src/core/contest-problem-assignment-user-tackling-submit-modal.tsx
import { gql, useMutation } from '@apollo/client';
import { css, cx } from 'emotion';
import React, { useRef, useState } from 'react';
import {
  ContestProblemAssignmentUserTacklingSubmitModalFragment,
  ContestProblemAssignmentUserTacklingSubmitModalSubmissionFieldFragment,
  SubmitMutation,
  SubmitMutationVariables,
} from '../generated/graphql-types';
import { useAsync } from '../util/async-hook';
import { buttonCss, buttonNormalizeCss, buttonPrimaryCss } from '../util/components/button';
import { modalBodyCss, modalFooterCss, modalHeaderCss } from '../util/components/modal';
import { loadFileContent } from '../util/file-load';
import { FragmentProps } from '../util/fragment-props';
import { textFragment } from './text';

export const contestProblemAssignmentUserTacklingSubmitModalFragment = gql`
  fragment ContestProblemAssignmentUserTacklingSubmitModalSubmissionFileType on SubmissionFileType {
    name
    title {
      ...Text
    }
  }

  fragment ContestProblemAssignmentUserTacklingSubmitModalSubmissionField on SubmissionField {
    name
    title {
      ...Text
    }
  }

  fragment ContestProblemAssignmentUserTacklingSubmitModalSubmissionFileTypeRule on SubmissionFileTypeRule {
    fields {
      name
    }
    extensions
    defaultType {
      ...ContestProblemAssignmentUserTacklingSubmitModalSubmissionFileType
    }
    recommendedTypes {
      ...ContestProblemAssignmentUserTacklingSubmitModalSubmissionFileType
    }
    otherTypes {
      ...ContestProblemAssignmentUserTacklingSubmitModalSubmissionFileType
    }
  }

  fragment ContestProblemAssignmentUserTacklingSubmitModal on ContestProblemAssignmentUserTackling {
    assignmentView {
      assignment {
        contest {
          name
        }
        problem {
          name
          title {
            ...Text
          }
          submissionFields {
            ...ContestProblemAssignmentUserTacklingSubmitModalSubmissionField
          }
          submissionFileTypeRules {
            ...ContestProblemAssignmentUserTacklingSubmitModalSubmissionFileTypeRule
          }
        }
      }
    }

    user {
      username
    }
  }

  ${textFragment}
`;

export function ContestProblemAssignmentUserTacklingSubmitModal({
  data,
  onSubmitSuccessful,
}: FragmentProps<ContestProblemAssignmentUserTacklingSubmitModalFragment> & {
  onSubmitSuccessful: (submissionId: string) => void;
}) {
  const [submit] = useMutation<SubmitMutation, SubmitMutationVariables>(
    gql`
      mutation Submit($submission: SubmissionInput!) {
        submit(submission: $submission) {
          id
        }
      }
    `,
    {
      refetchQueries: ['Main'],
      awaitRefetchQueries: true,
    },
  );

  const [loadFilesAndSubmit, { loading, error }] = useAsync(async (formData: FormData) => {
    const submission = await submit({
      variables: {
        submission: {
          contestName: data.assignmentView.assignment.contest.name,
          problemName: data.assignmentView.assignment.problem.name,
          username: data.user.username,
          files: await Promise.all(
            data.assignmentView.assignment.problem.submissionFields.map(async field => {
              const file = formData.get(`${field.name}.file`) as File;

              return {
                fieldName: field.name,
                fileTypeName: formData.get(`${field.name}.type`) as string,
                fileName: file.name,
                content: await loadFileContent(file),
              };
            }),
          ),
        },
      },
    });

    const submissionId = submission.data?.submit.id;
    if (submissionId !== undefined) {
      onSubmitSuccessful(submissionId);
    } else {
      throw new Error(`Cannot get new submission ID.`);
    }
  });

  return (
    <form
      onSubmit={e => {
        e.preventDefault();
        loadFilesAndSubmit(new FormData(e.target as HTMLFormElement));
      }}
      className={css`
        width: 40rem;
      `}
    >
      <div className={modalHeaderCss}>
        <h4>
          Solution of: <strong>{data.assignmentView.assignment.problem.title.variant}</strong>
        </h4>
      </div>
      <div
        className={cx(
          modalBodyCss,
          css`
            max-height: calc(100vh - 260px);
            overflow-y: auto;
          `,
        )}
      >
        {data.assignmentView.assignment.problem.submissionFields.map(f => (
          <FileInput key={f.name} data={data} field={f} />
        ))}
      </div>
      {error !== undefined && <>Error in submission: {error.message}</>}
      <div className={modalFooterCss}>
        <button className={cx(buttonCss, buttonPrimaryCss)} disabled={loading} type="submit">
          Submit
        </button>
      </div>
    </form>
  );
}

function FileInput({
  data,
  field,
}: FragmentProps<ContestProblemAssignmentUserTacklingSubmitModalFragment> & {
  field: ContestProblemAssignmentUserTacklingSubmitModalSubmissionFieldFragment;
}) {
  const fileFieldId = `${field.name}.file`;

  const fileInput = useRef<HTMLInputElement>(null);
  const [file, setFile] = useState<File | null>(null);

  return (
    <>
      <label
        className={css`
          display: block;
        `}
        htmlFor={fileFieldId}
      >
        {field.title.variant}
      </label>
      <input
        className={css`
          display: none;
        `}
        id={fileFieldId}
        name={fileFieldId}
        ref={fileInput}
        type="file"
        onChange={e => setFile(e.target.files !== null ? e.target.files[0] : null)}
      />
      <button
        className={cx(buttonCss, buttonPrimaryCss)}
        onClick={e => {
          fileInput.current?.click();
          e.preventDefault();
        }}
      >
        Choose file
      </button>
      {file !== null && (
        <dl
          className={css`
            display: flex;
            flex-flow: row wrap;

            & > dt {
              margin-bottom: 0px;
              min-width: 6rem;
            }

            & > dd {
              margin-bottom: 0px;
              margin-left: -6rem;
              padding-left: 8rem;
              flex: 1 1 100%;
            }
          `}
        >
          <dt>Name:</dt>
          <dd>{file.name}</dd>
          <dt>Type:</dt>
          <dd>
            <FileTypeInfo data={data} field={field} file={file} />
          </dd>

          <dt>Size:</dt>
          <dd>{file.size}</dd>
        </dl>
      )}
    </>
  );
}

function FileTypeInfo({
  data,
  field,
  file,
}: FragmentProps<ContestProblemAssignmentUserTacklingSubmitModalFragment> & {
  field: ContestProblemAssignmentUserTacklingSubmitModalSubmissionFieldFragment;
  file: File;
}) {
  const rule = getTypingRule({ data, field, file });

  const [overrideType, setOverrideType] = useState(false);
  const defaultType = overrideType ? null : rule.defaultType;

  const typeInputId = `${field.name}.type`;

  if (defaultType === null) {
    return (
      <select name={typeInputId}>
        {rule.recommendedTypes.map(t => (
          <option key={t.name} value={t.name}>
            {t.title.variant}
          </option>
        ))}
        {rule.otherTypes.map(t => (
          <option key={t.name} value={t.name}>
            {t.title.variant}
          </option>
        ))}
      </select>
    );
  } else {
    return (
      <>
        {defaultType.title.variant}(
        <button
          className={cx(
            buttonNormalizeCss,
            css`
              &:hover {
                text-decoration: underline;
              }
            `,
          )}
          onClick={() => setOverrideType(true)}
        >
          change
        </button>
        )
        <input type="hidden" name={typeInputId} value={defaultType.name} />
      </>
    );
  }
}

function getTypingRule({
  data,
  field,
  file,
}: FragmentProps<ContestProblemAssignmentUserTacklingSubmitModalFragment> & {
  field: ContestProblemAssignmentUserTacklingSubmitModalSubmissionFieldFragment;
  file: File;
}) {
  for (const rule of data.assignmentView.assignment.problem.submissionFileTypeRules) {
    const { fields = null, extensions = null } = rule;
    if (fields !== null && fields.find(f => f.name === field.name) === undefined) continue;
    if (extensions !== null && extensions.find(e => file.name.endsWith(e)) === undefined) continue;

    return rule;
  }
  throw new Error(`No file type rule matches the given field and file. The rules must include a catch-all rule.`);
}

// web/src/core/contest-problem-assignment-user-tackling-submit-modal.component.ts
import { Component, Input, OnInit, ViewEncapsulation } from '@angular/core';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';
import { Apollo } from 'apollo-angular';
import gql from 'graphql-tag';
import {
  ContestProblemAssignmentUserTacklingSubmitModalFragment,
  ContestProblemAssignmentUserTacklingSubmitModalSubmissionFieldFragment,
  SubmissionFileInput,
  SubmitMutation,
  SubmitMutationVariables,
} from '../generated/graphql-types';
import { FileLoadService } from '../util/file-load.service';
import { textFragment } from './material/text.pipe';

@Component({
  selector: 'app-contest-problem-assignment-user-tackling-submit-modal',
  templateUrl: './contest-problem-assignment-user-tackling-submit-modal.component.html',
  styleUrls: ['./contest-problem-assignment-user-tackling-submit-modal.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class ContestProblemAssignmentUserTacklingSubmitModalComponent implements OnInit {
  constructor(private readonly apollo: Apollo, private readonly fileLoadService: FileLoadService) {}

  @Input()
  modal!: NgbActiveModal;

  @Input()
  data!: ContestProblemAssignmentUserTacklingSubmitModalFragment;

  fieldStates: Record<
    string,
    {
      overrideDefaultType: boolean;
      file?: File;
    }
  > = {};

  submitting = false;

  ngOnInit() {
    for (const { name } of this.data.assignmentView.assignment.problem.submissionFields) {
      this.fieldStates[name] = {
        overrideDefaultType: false,
      };
    }
  }

  getTypingRule(file: File, field: ContestProblemAssignmentUserTacklingSubmitModalSubmissionFieldFragment) {
    for (const rule of this.data.assignmentView.assignment.problem.submissionFileTypeRules) {
      const { fields = null, extensions = null } = rule;
      if (fields !== null && fields.find(f => f.name === field.name) === undefined) continue;
      if (extensions !== null && extensions.find(e => file.name.endsWith(e)) === undefined) continue;

      return rule;
    }
    throw new Error(`No file type rule matches the given field and file. The rules must include a catch-all rule.`);
  }

  async submit(event: Event) {
    const formData = new FormData(event.target as HTMLFormElement);

    if (this.submitting) return;
    this.submitting = true;

    const files = await Promise.all(
      this.data.assignmentView.assignment.problem.submissionFields.map(async field =>
        this.getFileForField(field, formData),
      ),
    );

    const { data, errors } = await this.apollo
      .mutate<SubmitMutation, SubmitMutationVariables>({
        mutation: gql`
          mutation Submit($submission: SubmissionInput!) {
            submit(submission: $submission)
          }
        `,
        variables: {
          submission: {
            contestName: this.data.assignmentView.assignment.contest.name,
            problemName: this.data.assignmentView.assignment.problem.name,
            username: this.data.user.username,
            files,
          },
        },
        refetchQueries: ['Main'],
        awaitRefetchQueries: true,
      })
      .toPromise();

    if (data === undefined || data === null || errors !== undefined) {
      throw new Error('error in submit');
    }

    this.modal.close();
  }

  private async getFileForField(
    field: ContestProblemAssignmentUserTacklingSubmitModalSubmissionFieldFragment,
    formData: FormData,
  ): Promise<SubmissionFileInput> {
    const file = formData.get(`${field.name}.file`) as File;

    return {
      fieldName: field.name,
      fileTypeName: formData.get(`${field.name}.type`) as string,
      fileName: file.name,
      content: await this.fileLoadService.loadFileContent(file),
    };
  }
}

export const contestProblemAssignmentUserTacklingSubmitModalFragment = gql`
  fragment ContestProblemAssignmentUserTacklingSubmitModalSubmissionFileType on SubmissionFileType {
    name
    title {
      ...Text
    }
  }

  fragment ContestProblemAssignmentUserTacklingSubmitModalSubmissionField on SubmissionField {
    name
    title {
      ...Text
    }
  }

  fragment ContestProblemAssignmentUserTacklingSubmitModalSubmissionFileTypeRule on SubmissionFileTypeRule {
    fields {
      name
    }
    extensions
    defaultType {
      ...ContestProblemAssignmentUserTacklingSubmitModalSubmissionFileType
    }
    recommendedTypes {
      ...ContestProblemAssignmentUserTacklingSubmitModalSubmissionFileType
    }
    otherTypes {
      ...ContestProblemAssignmentUserTacklingSubmitModalSubmissionFileType
    }
  }

  fragment ContestProblemAssignmentUserTacklingSubmitModal on ContestProblemAssignmentUserTackling {
    assignmentView {
      assignment {
        contest {
          name
        }
        problem {
          name
          title {
            ...Text
          }
          submissionFields {
            ...ContestProblemAssignmentUserTacklingSubmitModalSubmissionField
          }
          submissionFileTypeRules {
            ...ContestProblemAssignmentUserTacklingSubmitModalSubmissionFileTypeRule
          }
        }
      }
    }

    user {
      username
    }
  }

  ${textFragment}
`;

<form class="submit-modal" (ngSubmit)="submit($event)">
  <div class="submit-modal-header">
    <h4>
      Solution of: <strong>{{ data.assignmentView.assignment.problem.title | text }}</strong>
    </h4>
  </div>
  <div class="submit-modal-body">
    <ng-container *ngFor="let field of data.assignmentView.assignment.problem.submissionFields">
      <ng-container *ngIf="fieldStates[field.name] as state">
        <label class="submit-field-label" [for]="field.name + '.file'">{{ field.title | text }}</label>
        <input #input class="submit-field-input" [id]="field.name + '.file'" [name]="field.name + '.file'" type="file"
          (change)="state.file = $event.target.files[0]" />
        <button class="submit-field-choose" (click)="input.click(); $event.preventDefault()">Choose file</button>
        <dl *ngIf="state.file! as file" class="submit-field-info">
          <dt>Name:</dt>
          <dd>{{ file.name }}</dd>
          <dt>Type:</dt>

          <ng-container *ngIf="getTypingRule(file, field) as typeRule">
            <dd [ngSwitch]="state.overrideDefaultType ? null : typeRule.defaultType">
              <ng-container *ngSwitchCase="null">
                <select [name]="field.name + '.type'" class="submit-field-select-type">
                  <ng-container *ngFor="let type of typeRule.recommendedTypes">
                    <option [value]="type.name">{{ type.title | text }}</option>
                  </ng-container>
                  <ng-container *ngFor="let type of typeRule.otherTypes">
                    <option [value]="type.name">{{ type.title | text }}</option>
                  </ng-container>
                </select>
              </ng-container>
              <ng-container *ngSwitchDefault>
                {{ typeRule.defaultType!.title | text }}
                (<a href="#" role="button" class="submit-field-change-type"
                  (click)="state.overrideDefaultType = true; $event.preventDefault()">change</a>)
                <input type="hidden" [name]="field.name + '.type'" [value]="typeRule.defaultType!.name" />
              </ng-container>
            </dd>
          </ng-container>

          <dt>Size:</dt>
          <dd>{{ file.size | filesize }}</dd>
        </dl>
      </ng-container>
    </ng-container>
  </div>
  <div class="submit-modal-footer">
    <button class="submit-modal-submit" [disabled]="submitting" type="submit">Submit</button>
  </div>
</form>
