// web-react/src/core/contest-problem-assignment-user-tackling-aside.tsx
import { gql } from '@apollo/client';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import React from 'react';
import { ContestProblemAssignmentUserTacklingAsideFragment } from '../generated/graphql-types';
import { FragmentProps } from '../util/fragment-props';
import { contestProblemAssignmentUserTacklingSubmissionListModalFragment } from './contest-problem-assignment-user-tackling-submission-list-modal';
import { contestProblemAssignmentUserTacklingSubmitModalFragment } from './contest-problem-assignment-user-tackling-submit-modal';
import { submissionModalFragment } from './submission-modal';

export const contestProblemAssignmentUserTacklingAsideFragment = gql`
  fragment ContestProblemAssignmentUserTacklingAside on ContestProblemAssignmentUserTackling {
    canSubmit
    submissions {
      id
      officialEvaluation {
        status
      }

      ...SubmissionModal
    }

    ...ContestProblemAssignmentUserTacklingSubmitModal
    ...ContestProblemAssignmentUserTacklingSubmissionListModal
  }

  ${submissionModalFragment}
  ${contestProblemAssignmentUserTacklingSubmitModalFragment}
  ${contestProblemAssignmentUserTacklingSubmissionListModalFragment}
`;

export function ContestProblemAssignmentUserTacklingAside({
  data,
}: FragmentProps<ContestProblemAssignmentUserTacklingAsideFragment>) {
  const lastSubmission = data.submissions.length > 0 ? data.submissions[data.submissions.length - 1] : null;

  return (
    <>
      {data.canSubmit && (
        <button className="btn btn-block btn-success">
          <FontAwesomeIcon icon="paper-plane" />
          Submit a solution
        </button>
      )}

      {lastSubmission !== null && (
        <>
          <button className="btn btn-block btn-outline">
            {lastSubmission.officialEvaluation?.status === 'PENDING' && <FontAwesomeIcon icon="history" />}
            {lastSubmission.officialEvaluation?.status !== 'PENDING' && <FontAwesomeIcon icon="spinner" pulse={true} />}
            Last submission
          </button>
          <button className="btn btn-block btn-outline">
            <FontAwesomeIcon icon="list" />
            All submissions
          </button>
        </>
      )}
    </>
  );
}

// web/src/core/contest-problem-assignment-user-tackling-aside.component.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';
import gql from 'graphql-tag';
import { ContestProblemAssignmentUserTacklingAsideFragment } from '../generated/graphql-types';
import { contestProblemAssignmentUserTacklingSubmissionListModalFragment } from './contest-problem-assignment-user-tackling-submission-list-modal.component';
import { contestProblemAssignmentUserTacklingSubmitModalFragment } from './contest-problem-assignment-user-tackling-submit-modal.component';
import { submissionModalFragment } from './submission-modal.component';

@Component({
  selector: 'app-contest-problem-assignment-user-tackling-aside',
  templateUrl: './contest-problem-assignment-user-tackling-aside.component.html',
  styleUrls: ['./contest-problem-assignment-user-tackling-aside.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class ContestProblemAssignmentUserTacklingAsideComponent {
  constructor(readonly modalService: NgbModal) {}

  @Input()
  data!: ContestProblemAssignmentUserTacklingAsideFragment;
}

export const contestProblemAssignmentUserTacklingAsideFragment = gql`
  fragment ContestProblemAssignmentUserTacklingAside on ContestProblemAssignmentUserTackling {
    canSubmit
    submissions {
      id
      officialEvaluation {
        status
      }

      ...SubmissionModal
    }

    ...ContestProblemAssignmentUserTacklingSubmitModal
    ...ContestProblemAssignmentUserTacklingSubmissionListModal
  }

  ${submissionModalFragment}
  ${contestProblemAssignmentUserTacklingSubmitModalFragment}
  ${contestProblemAssignmentUserTacklingSubmissionListModalFragment}
`;

<ng-container *ngIf="data.canSubmit">
  <button class="problem-submit" (click)="modalService.open(submitDialog)">
    <fa-icon icon="paper-plane"></fa-icon>
    Submit a solution
    <ng-template #submitDialog let-modal>
      <app-contest-problem-assignment-user-tackling-submit-modal [data]="data" [modal]="modal">
      </app-contest-problem-assignment-user-tackling-submit-modal>
    </ng-template>
  </button>
</ng-container>

<ng-container *ngIf="data.submissions[data.submissions.length - 1] as lastSubmission">
  <button class="problem-last-submission-button" (click)="modalService.open(lastSubmissionModal, { size: 'lg' })">
    <fa-icon *ngIf="lastSubmission.officialEvaluation?.status !== 'PENDING'" icon="history"></fa-icon>
    <fa-icon *ngIf="lastSubmission.officialEvaluation?.status === 'PENDING'" icon="spinner" [pulse]="true">
    </fa-icon>
    Last submission
    <ng-template #lastSubmissionModal let-modal>
      <app-submission-modal [modal]="modal" [data]="lastSubmission">
      </app-submission-modal>
    </ng-template>
  </button>

  <button class="problem-submission-list-button" (click)="modalService.open(submissionListModal, { size: 'xl' })">
    <fa-icon icon="list"></fa-icon>
    All submissions
    <ng-template #submissionListModal let-modal>
      <app-contest-problem-assignment-user-tackling-submission-list-modal [modal]="modal" [data]="data">
      </app-contest-problem-assignment-user-tackling-submission-list-modal>
    </ng-template>
  </button>

</ng-container>
