// web-react/src/core/contest-problem-assignment-view-aside.tsx
import { gql } from '@apollo/client';
import React from 'react';
import { ContestProblemAssignmentViewAsideFragment } from '../generated/graphql-types';
import { FragmentProps } from '../util/fragment-props';
import {
  ContestProblemAssignmentUserTacklingAside,
  contestProblemAssignmentUserTacklingAsideFragment,
} from './contest-problem-assignment-user-tackling-aside';
import { gradeFieldFragment, scoreFieldFragment } from './fields/grade-field';
import { mediaDownloadFragment } from './media-download';
import { mediaInlineFragment } from './media-inline';
import { textFragment } from './text';

export const contestProblemAssignmentViewAsideFragment = gql`
  fragment ContestProblemAssignmentViewAside on ContestProblemAssignmentView {
    assignment {
      id
      problem {
        id
        name
        title {
          ...Text
        }
        statement {
          ...MediaInline
          ...MediaDownload
        }
        attachments {
          title {
            ...Text
          }
          media {
            ...MediaDownload
          }
        }
      }
    }

    totalScoreField {
      ...ScoreField
    }

    awardAssignmentViews {
      assignment {
        id
        award {
          id
          name
          title {
            ...Text
          }
        }
      }

      gradeField {
        ...GradeField
      }
    }

    tackling {
      ...ContestProblemAssignmentUserTacklingAside
    }
  }

  ${textFragment}
  ${mediaInlineFragment}
  ${mediaDownloadFragment}
  ${scoreFieldFragment}
  ${gradeFieldFragment}
  ${contestProblemAssignmentUserTacklingAsideFragment}
`;

export function ContestProblemAssignmentViewAside({ data }: FragmentProps<ContestProblemAssignmentViewAsideFragment>) {
  return <>{data.tackling !== null && <ContestProblemAssignmentUserTacklingAside data={data.tackling} />}</>;
}

// web/src/core/contest-problem-assignment-view-aside.component.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';
import gql from 'graphql-tag';
import { ContestProblemAssignmentViewAsideFragment } from '../generated/graphql-types';
import { contestProblemAssignmentUserTacklingAsideFragment } from './contest-problem-assignment-user-tackling-aside.component';
import { gradeVariableFragment } from './grading/grade-variable.component';
import { scoreVariableFragment } from './grading/score-variable.component';
import { mediaDownloadFragment } from './material/media-download.component';
import { mediaInlineFragment } from './material/media-inline.component';
import { textFragment } from './material/text.pipe';

@Component({
  selector: 'app-contest-problem-assignment-view-aside',
  templateUrl: './contest-problem-assignment-view-aside.component.html',
  styleUrls: ['./contest-problem-assignment-view-aside.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class ContestProblemAssignmentViewAsideComponent {
  @Input()
  data!: ContestProblemAssignmentViewAsideFragment;
}

export const contestProblemAssignmentViewAsideFragment = gql`
  fragment ContestProblemAssignmentViewAside on ContestProblemAssignmentView {
    assignment {
      problem {
        name
        title {
          ...Text
        }
        statement {
          ...MediaInline
          ...MediaDownload
        }
        attachments {
          title {
            ...Text
          }
          media {
            ...MediaDownload
          }
        }
      }
    }

    totalScoreVariable {
      ...ScoreVariable
    }

    awardAssignmentViews {
      assignment {
        award {
          name
          title {
            ...Text
          }
        }
      }

      gradeVariable {
        ...GradeVariable
      }
    }

    tackling {
      ...ContestProblemAssignmentUserTacklingAside
    }
  }

  ${textFragment}
  ${mediaInlineFragment}
  ${mediaDownloadFragment}
  ${scoreVariableFragment}
  ${gradeVariableFragment}
  ${contestProblemAssignmentUserTacklingAsideFragment}
`;

<app-contest-problem-assignment-user-tackling-aside [data]="data.tackling"></app-contest-problem-assignment-user-tackling-aside>
<div class="problem-info">
  <ng-container *ngIf="data.awardAssignmentViews.length > 0">
    <h3 class="problem-award-list-title">Awards</h3>
    <div class="problem-award-list">
      <ng-container *ngFor="let awardAssignmentView of data.awardAssignmentViews">
        <div class="problem-award" [title]="awardAssignmentView.assignment.award.title | text">
          {{ awardAssignmentView.assignment.award.title | text }}
          <span class="problem-award-grading" [appValence]="awardAssignmentView.gradeVariable">
            <app-grade-variable [data]="awardAssignmentView.gradeVariable"></app-grade-variable>
          </span>
        </div>
      </ng-container>
    </div>
  </ng-container>
  <ng-container *ngIf="data.assignment.problem.attachments.length > 0">
    <h3 class="problem-attachment-list-title">Attachments</h3>
    <div class="problem-attachment-list">
      <ng-container *ngFor="let attachment of data.assignment.problem.attachments">
        <app-media-download [data]="attachment.media"></app-media-download>
      </ng-container>
    </div>
  </ng-container>
  <h2 class="problem-download-statement-title">Statement file</h2>
  <app-media-download class="problem-download-statement" [data]="data.assignment.problem.statement"></app-media-download>
</div>
