// web-react/src/core/main-view.tsx
import { gql } from '@apollo/client';
import React from 'react';
import { MainViewFragment } from '../generated/graphql-types';
import { contestViewFragment } from './contest-view';
import { topBarFragment } from './top-bar';

export function MainView({ data }: { data: MainViewFragment }) {
  return <div>{JSON.stringify(data)}</div>;
}

export const mainViewFragment = gql`
  fragment MainView on MainView {
    ...TopBar
    contestView {
      ...ContestView
    }
  }

  ${topBarFragment}
  ${contestViewFragment}
`;

// web/src/core/main-view.component.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';
import gql from 'graphql-tag';
import { MainViewFragment } from '../generated/graphql-types';
import { contestViewFragment } from './contest-view.component';
import { topBarFragment } from './top-bar.component';

@Component({
  selector: 'app-main-view',
  templateUrl: './main-view.component.html',
  styleUrls: ['./main-view.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class MainViewComponent {
  @Input()
  data!: MainViewFragment;
}

export const mainViewFragment = gql`
  fragment MainView on MainView {
    ...TopBar
    contestView {
      ...ContestView
    }
  }

  ${topBarFragment}
  ${contestViewFragment}
`;

<app-top-bar [data]="data"></app-top-bar>
<ng-container *ngIf="data.contestView as contestView">
  <app-contest-view [data]="contestView"></app-contest-view>
</ng-container>
