// web-react/src/core/media-inline.tsx
import { gql } from '@apollo/client';
import React, { useEffect, useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { MediaInlineFragment } from '../generated/graphql-types';
import { FragmentProps } from '../util/fragment-props';

export const mediaInlineFragment = gql`
  fragment MediaInline on Media {
    variant {
      name
      type
      url
    }
  }
`;

export function MarkdownMediaInline({ data }: FragmentProps<MediaInlineFragment>) {
  const [md, setMd] = useState<string>('');
  const [error, setError] = useState<unknown>();

  useEffect(() => {
    fetch(data.variant.url)
      .then(r => r.text())
      .then(t => {
        setMd(t);
      })
      .catch(e => {
        setError(e);
      });
  }, [data]);

  if (error !== undefined) return <p>Error while loading markdown: {`${error}`}</p>;

  return <ReactMarkdown source={md}></ReactMarkdown>;
}

export function MediaInline({ data }: FragmentProps<MediaInlineFragment>) {
  switch (data.variant.type) {
    case 'text/markdown':
      return <MarkdownMediaInline data={data}></MarkdownMediaInline>;
    default:
      return <iframe className="inline-file-iframe" src={data.variant.url}></iframe>;
  }
}

// web/src/core/media-inline.component.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';
import gql from 'graphql-tag';
import { MediaInlineFragment } from '../generated/graphql-types';

@Component({
  selector: 'app-media-inline',
  templateUrl: './media-inline.component.html',
  styleUrls: ['./media-inline.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class MediaInlineComponent {
  @Input()
  data!: MediaInlineFragment;
}

export const mediaInlineFragment = gql`
  fragment MediaInline on Media {
    variant {
      name
      type
      url
    }
  }
`;

<ng-container [ngSwitch]="data.variant.type">
  <markdown class="inline-file-markdown" *ngSwitchCase="'text/markdown'" katex [src]="data.variant.url"></markdown>
  <iframe *ngSwitchDefault class="inline-file-iframe"
    [attr.src]="data.variant.url | bypassSanitizer: 'ResourceUrl'"></iframe>
</ng-container>
