// web-react/src/core/submission-modal.tsx
import { gql } from '@apollo/client';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { AgGridReact } from 'ag-grid-react';
import { css, cx } from 'emotion';
import React from 'react';
import { RecordFragment, SubmissionModalFragment } from '../generated/graphql-types';
import { buttonCss, buttonPrimaryCss } from '../util/components/button';
import { gridCss } from '../util/components/grid';
import { modalFooterCss, modalHeaderCss } from '../util/components/modal';
import { FragmentProps } from '../util/fragment-props';
import { columnFragment, getFieldColumns, recordFragment } from './field-table';
import { textFragment } from './text';

export const submissionModalFragment = gql`
  fragment SubmissionModal on Submission {
    id
    # TODO: files
    createdAt {
      local
    }
    officialEvaluation {
      status
    }
    problem {
      id
      title {
        ...Text
      }
    }
    feedbackTable {
      columns {
        ...Column
      }
      rows {
        ...Record
      }
    }
  }

  ${textFragment}
  ${recordFragment}
  ${columnFragment}
`;

export function SubmissionModal({ data }: FragmentProps<SubmissionModalFragment>) {
  return (
    <>
      <div
        className={css`
          width: 80vw;
          overflow: auto;
        `}
      >
        <div className={modalHeaderCss}>
          <h5>
            {/* TODO: submission index, e.g., Submission #6 for: My Problem */}
            Submission for: <strong>{data.problem.title.variant}</strong>
          </h5>
        </div>
        <div
          className={
            data.officialEvaluation?.status === 'PENDING'
              ? css`
                  background-color: rgba(0, 0, 0, 0.1);
                  text-align: center;
                `
              : css`
                  display: none;
                `
          }
        >
          <FontAwesomeIcon icon="spinner" pulse /> Evaluating...
        </div>

        <div className={cx(gridCss)}>
          <AgGridReact
            columnDefs={getFieldColumns(data.feedbackTable.columns, (row: RecordFragment) => row)}
            domLayout="autoHeight"
            rowData={data.feedbackTable.rows}
          />
        </div>
        <div className={modalFooterCss}>
          <button onClick={() => {}} className={cx(buttonCss, buttonPrimaryCss)}>
            Close
          </button>
        </div>
      </div>
    </>
  );
}

// web/src/core/submission-modal.component.ts
import { Component, Input, OnChanges, ViewEncapsulation } from '@angular/core';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';
import { Apollo, QueryRef } from 'apollo-angular';
import gql from 'graphql-tag';
import { Observable } from 'rxjs';
import { map, tap } from 'rxjs/operators';
import {
  RecordFragment,
  SubmissionModalFragment,
  SubmissionQuery,
  SubmissionQueryVariables,
} from '../generated/graphql-types';
import { columnFragment, getFieldColumns, recordFragment } from './data/field-table';
import { textFragment } from './material/text.pipe';

@Component({
  selector: 'app-submission-modal',
  templateUrl: './submission-modal.component.html',
  styleUrls: ['./submission-modal.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class SubmissionModalComponent implements OnChanges {
  constructor(private readonly apollo: Apollo) {}

  @Input()
  modal!: NgbActiveModal;

  @Input()
  id!: string;

  queryRef!: QueryRef<SubmissionQuery, SubmissionQueryVariables>;
  dataObservable!: Observable<SubmissionQuery>;

  ngOnChanges() {
    this.queryRef = this.apollo.watchQuery<SubmissionQuery, SubmissionQueryVariables>({
      query: gql`
        query Submission($id: ID!) {
          submission(id: $id) {
            ...SubmissionModal
          }
        }

        ${submissionModalFragment}
      `,
      variables: {
        id: this.id,
      },
      pollInterval: 500,
    });
    this.dataObservable = this.queryRef.valueChanges.pipe(
      map(({ data }) => data),
      tap(data => {
        if (data.submission.officialEvaluation?.status !== 'PENDING') {
          this.queryRef.stopPolling();
        }
      }),
    );
  }

  getColumns(data: SubmissionModalFragment) {
    return getFieldColumns(data.feedbackTable.columns, (row: RecordFragment) => row);
  }
}

export const submissionModalFragment = gql`
  fragment SubmissionModal on Submission {
    id
    # TODO: files
    createdAt {
      local
    }
    officialEvaluation {
      status
    }
    problem {
      id
      title {
        ...Text
      }
    }
    feedbackTable {
      columns {
        ...Column
      }
      rows {
        ...Record
      }
    }
  }

  ${textFragment}
  ${recordFragment}
  ${columnFragment}
`;

<ng-container *ngIf="(dataObservable | async)?.submission as data">
  <div class="submission-dialog-header">
    <h5>
      Submission for: <strong>{{ data.problem.title | text }}</strong>
    </h5>
  </div>
  <div class="submission-pending" *ngIf="data.officialEvaluation?.status === 'PENDING'">
    <fa-icon icon="spinner" [pulse]="true"></fa-icon> Evaluating...
  </div>
  <div class="submission-dialog-body">
    <ag-grid-angular class="ag-theme-balham" domLayout="autoHeight" [rowData]="data.feedbackTable.rows"
      [columnDefs]="data | applyPure: getColumns" (gridSizeChanged)="$event.api.sizeColumnsToFit()">
    </ag-grid-angular>

  </div>
  <div class="submission-dialog-footer">
    <button (click)="modal.close()" class="submission-dialog-close">Close</button>
  </div>feedbackTable.columns
</ng-container>
