// web/src/core/data/field.tsx
import { gql } from '@apollo/client';
import React from 'react';
import { FieldFragment } from '../../generated/graphql-types';
import { unexpected } from '../../util/check';
import { FragmentProps } from '../../util/fragment-props';
import { DateTimeField, dateTimeFieldFragment } from './date-time-field';
import { FulfillmentField, fulfillmentFieldFragment, ScoreField, scoreFieldFragment } from './grade-field';
import { HeaderField, headerFieldFragment } from './header-field';
import { MemoryUsageField, memoryUsageFieldFragment } from './memory-usage-field';
import { MessageField, messageFieldFragment } from './message-field';
import { TimeUsageField, timeUsageFieldFragment } from './time-usage-field';

export function Field({ data }: FragmentProps<FieldFragment>) {
  switch (data.__typename) {
    case 'TimeUsageField':
      return <TimeUsageField data={data} />;
    case 'MemoryUsageField':
      return <MemoryUsageField data={data} />;
    case 'FulfillmentField':
      return <FulfillmentField data={data} />;
    case 'ScoreField':
      return <ScoreField data={data} />;
    case 'MessageField':
      return <MessageField data={data} />;
    case 'HeaderField':
      return <HeaderField data={data} />;
    case 'DateTimeField':
      return <DateTimeField data={data} />;
    default:
      return unexpected(data);
  }
}

export const fieldFragment = gql`
  fragment Field on Field {
    ... on FulfillmentField {
      ...FulfillmentField
    }
    ... on ScoreField {
      ...ScoreField
    }
    ... on HeaderField {
      ...HeaderField
    }
    ... on MessageField {
      ...MessageField
    }
    ... on TimeUsageField {
      ...TimeUsageField
    }
    ... on MemoryUsageField {
      ...MemoryUsageField
    }
    ... on DateTimeField {
      ...DateTimeField
    }
  }

  ${headerFieldFragment}
  ${fulfillmentFieldFragment}
  ${scoreFieldFragment}
  ${memoryUsageFieldFragment}
  ${messageFieldFragment}
  ${timeUsageFieldFragment}
  ${dateTimeFieldFragment}
`;

// web/src/core/data/field.component.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';
import gql from 'graphql-tag';
import { FieldFragment } from '../../generated/graphql-types';
import { fulfillmentFieldFragment } from '../grading/fulfillment-field.component';
import { scoreFieldFragment } from '../grading/score-field.component';
import { indexFieldFragment } from './index-field.component';
import { memoryUsageFieldFragment } from './memory-usage-field.component';
import { messageFieldFragment } from './message-field.component';
import { timeUsageFieldFragment } from './time-usage-field.component';
import { titleFieldFragment } from './title-field.component';

@Component({
  selector: 'app-field',
  templateUrl: './field.component.html',
  styleUrls: ['./field.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class FieldComponent {
  @Input()
  data!: FieldFragment;
}

export const fieldFragment = gql`
  fragment Field on Field {
    ... on FulfillmentField {
      ...FulfillmentField
    }
    ... on ScoreField {
      ...ScoreField
    }
    ... on IndexField {
      ...IndexField
    }
    ... on TitleField {
      ...TitleField
    }
    ... on MessageField {
      ...MessageField
    }
    ... on TimeUsageField {
      ...TimeUsageField
    }
    ... on MemoryUsageField {
      ...MemoryUsageField
    }
  }

  ${fulfillmentFieldFragment}
  ${scoreFieldFragment}
  ${indexFieldFragment}
  ${memoryUsageFieldFragment}
  ${messageFieldFragment}
  ${timeUsageFieldFragment}
  ${titleFieldFragment}
`;

<ng-container [ngSwitch]="data.__typename">
  <app-score-field *ngSwitchCase="'ScoreField'" [data]="data"></app-score-field>
  <app-fulfillment-field *ngSwitchCase="'FulfillmentField'" [data]="data"></app-fulfillment-field>
  <app-memory-usage-field *ngSwitchCase="'MemoryUsageField'" [data]="data"></app-memory-usage-field>
  <app-time-usage-field *ngSwitchCase="'TimeUsageField'" [data]="data"></app-time-usage-field>
  <app-message-field *ngSwitchCase="'MessageField'" [data]="data"></app-message-field>
  <app-title-field *ngSwitchCase="'TitleField'" [data]="data"></app-title-field>
  <app-index-field *ngSwitchCase="'IndexField'" [data]="data"></app-index-field>
</ng-container>
