// web/src/core/fields/index-field.tsx
import { gql } from '@apollo/client';
import React from 'react';
import { IndexFieldFragment } from '../../generated/graphql-types';
import { FragmentProps } from '../../util/fragment-props';

export function IndexField({ data }: FragmentProps<IndexFieldFragment>) {
  return <>{data.index}</>;
}

export const indexFieldFragment = gql`
  fragment IndexField on IndexField {
    index
  }
`;

// web/src/core/data/index-field.component.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';
import gql from 'graphql-tag';
import { IndexFieldFragment } from '../../generated/graphql-types';

@Component({
  selector: 'app-index-field',
  templateUrl: './index-field.component.html',
  styleUrls: ['./index-field.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class IndexFieldComponent {
  @Input()
  data!: IndexFieldFragment;
}

export const indexFieldFragment = gql`
  fragment IndexField on IndexField {
    index
  }
`;

{{ data.index }}
