// web/src/core/data/memory-usage-field.component.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';
import gql from 'graphql-tag';
import { MemoryUsageFieldFragment, MemoryUsageFragment } from '../../generated/graphql-types';

@Component({
  selector: 'app-memory-usage-field',
  templateUrl: './memory-usage-field.component.html',
  styleUrls: ['./memory-usage-field.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class MemoryUsageFieldComponent {
  @Input()
  data!: MemoryUsageFieldFragment;

  // tslint:disable: no-magic-numbers
  displayMemoryUsage(memoryUsage: MemoryUsageFragment) {
    const { memoryUsageMaxRelevant } = this.data;

    const { bytes } = memoryUsage;
    const kb = bytes / 1024;
    const mb = kb / 1024;

    if (memoryUsageMaxRelevant.bytes > 100e6) {
      return `${mb.toFixed(1)} MB`;
    } else if (memoryUsageMaxRelevant.bytes > 10e6) {
      return `${mb.toFixed(2)} MB`;
    } else if (memoryUsageMaxRelevant.bytes > 1e6) {
      return `${kb.toFixed(0)} KB`;
    } else if (memoryUsageMaxRelevant.bytes > 100e3) {
      return `${kb.toFixed(1)} KB`;
    } else if (memoryUsageMaxRelevant.bytes > 10e3) {
      return `${kb.toFixed(2)} KB`;
    } else {
      return `${kb.toFixed(3)} KB`;
    }
  }
}

export const memoryUsageFieldFragment = gql`
  fragment MemoryUsage on MemoryUsage {
    bytes
  }

  fragment MemoryUsageField on MemoryUsageField {
    memoryUsage {
      ...MemoryUsage
    }
    memoryUsageMaxRelevant {
      ...MemoryUsage
    }
    memoryUsagePrimaryWatermark {
      ...MemoryUsage
    }
  }
`;

<span class="memory-usage">
  <ng-container *ngIf="data.memoryUsage as memoryUsage">{{displayMemoryUsage(memoryUsage)}}</ng-container>
  <ng-container *ngIf="data.memoryUsagePrimaryWatermark as memoryUsage"> / {{displayMemoryUsage(memoryUsage)}}</ng-container>
</span>

// web/src/core/data/memory-usage-field.tsx
import { gql } from '@apollo/client';
import React from 'react';
import { MemoryUsageFieldFragment, MemoryUsageFragment } from '../../generated/graphql-types';
import { FragmentProps } from '../../util/fragment-props';

export function MemoryUsageField({ data }: FragmentProps<MemoryUsageFieldFragment>) {
  // tslint:disable: no-magic-numbers
  const displayMemoryUsage = (memoryUsage: MemoryUsageFragment) => {
    const { memoryUsageMaxRelevant } = data;

    const { bytes } = memoryUsage;
    const kb = bytes / 1024;
    const mb = kb / 1024;

    const truncate = memoryUsageMaxRelevant !== null;
    const scale = memoryUsageMaxRelevant ?? memoryUsage;

    if (scale.bytes > 100e6) {
      return `${truncate ? mb.toFixed(1) : mb} MB`;
    } else if (scale.bytes > 10e6) {
      return `${truncate ? mb.toFixed(2) : mb} MB`;
    } else if (scale.bytes > 1e6) {
      return `${truncate ? kb.toFixed(0) : mb} KB`;
    } else if (scale.bytes > 100e3) {
      return `${truncate ? kb.toFixed(1) : mb} KB`;
    } else if (scale.bytes > 10e3) {
      return `${truncate ? kb.toFixed(2) : mb} KB`;
    } else {
      return `${truncate ? kb.toFixed(3) : mb} KB`;
    }
  };

  return (
    <span className="memory-usage">
      {data.memoryUsage !== null && displayMemoryUsage(data.memoryUsage)}
      {data.memoryUsageWatermark !== null && <small> / {displayMemoryUsage(data.memoryUsageWatermark)}</small>}
    </span>
  );
}

export const memoryUsageFieldFragment = gql`
  fragment MemoryUsage on MemoryUsage {
    bytes
  }

  fragment MemoryUsageField on MemoryUsageField {
    memoryUsage {
      ...MemoryUsage
    }
    memoryUsageMaxRelevant {
      ...MemoryUsage
    }
    memoryUsageWatermark {
      ...MemoryUsage
    }
  }
`;
