// web/src/core/fields/message-field.tsx
import { gql } from '@apollo/client';
import React from 'react';
import { MessageFieldFragment } from '../../generated/graphql-types';
import { FragmentProps } from '../../util/fragment-props';
import { Text, textFragment } from '../text';

export function MessageField({ data }: FragmentProps<MessageFieldFragment>) {
  return <>{data.message !== null && <Text data={data.message} />}</>;
}

export const messageFieldFragment = gql`
  fragment MessageField on MessageField {
    message {
      ...Text
    }
  }

  ${textFragment}
`;

// web/src/core/data/message-field.component.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';
import gql from 'graphql-tag';
import { MessageFieldFragment } from '../../generated/graphql-types';
import { textFragment } from '../material/text.pipe';

@Component({
  selector: 'app-message-field',
  templateUrl: './message-field.component.html',
  styleUrls: ['./message-field.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class MessageFieldComponent {
  @Input()
  data!: MessageFieldFragment;
}

export const timeUsageFieldFragment = gql`
  fragment MessageField on MessageField {
    message {
      ...Text
    }
  }

  ${textFragment}
`;

{{ data.message | text }}
