// web/src/core/fields/time-usage-field.tsx
import { gql } from '@apollo/client';
import { Duration } from 'luxon';
import React from 'react';
import { TimeUsageFieldFragment, TimeUsageFragment } from '../../generated/graphql-types';
import { FragmentProps } from '../../util/fragment-props';

export function TimeUsageField({ data }: FragmentProps<TimeUsageFieldFragment>) {
  const displayTimeUsage = (timeUsage: TimeUsageFragment) => {
    const { timeUsageMaxRelevant } = data;

    const extraPrecision = 3;
    const fractionDigits = Math.max(Math.round(-Math.log10(timeUsageMaxRelevant.seconds) + extraPrecision), 0);
    const millisPrecision = 3;

    const duration = Duration.fromObject({ seconds: timeUsage.seconds });
    if (fractionDigits > millisPrecision) {
      return `${duration.as('milliseconds').toFixed(fractionDigits - millisPrecision)} ms`;
    } else {
      return `${duration.as('seconds').toFixed(fractionDigits)} s`;
    }
  };

  return (
    <span className="time-usage">
      {data.timeUsage !== null && displayTimeUsage(data.timeUsage)}
      {data.timeUsagePrimaryWatermark !== null && <small> / {displayTimeUsage(data.timeUsagePrimaryWatermark)}</small>}
    </span>
  );
}

export const timeUsageFieldFragment = gql`
  fragment TimeUsage on TimeUsage {
    seconds
  }

  fragment TimeUsageField on TimeUsageField {
    timeUsage {
      ...TimeUsage
    }
    timeUsageMaxRelevant {
      ...TimeUsage
    }
    timeUsagePrimaryWatermark {
      ...TimeUsage
    }
  }
`;

// web/src/core/data/time-usage-field.component.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';
import gql from 'graphql-tag';
import { Duration } from 'luxon';
import { TimeUsageFieldFragment, TimeUsageFragment } from '../../generated/graphql-types';

@Component({
  selector: 'app-time-usage-field',
  templateUrl: './time-usage-field.component.html',
  styleUrls: ['./time-usage-field.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class TimeUsageFieldComponent {
  @Input()
  data!: TimeUsageFieldFragment;

  displayTimeUsage(timeUsage: TimeUsageFragment) {
    const { timeUsageMaxRelevant } = this.data;

    const extraPrecision = 3;
    const fractionDigits = Math.max(Math.round(-Math.log10(timeUsageMaxRelevant.seconds) + extraPrecision), 0);
    const millisPrecision = 3;

    const duration = Duration.fromObject({ seconds: timeUsage.seconds });
    if (fractionDigits > millisPrecision) {
      return `${duration.as('milliseconds').toFixed(fractionDigits - millisPrecision)} ms`;
    } else {
      return `${duration.as('seconds').toFixed(fractionDigits)} s`;
    }
  }
}

export const timeUsageFieldFragment = gql`
  fragment TimeUsage on TimeUsage {
    seconds
  }

  fragment TimeUsageField on TimeUsageField {
    timeUsage {
      ...TimeUsage
    }
    timeUsageMaxRelevant {
      ...TimeUsage
    }
    timeUsagePrimaryWatermark {
      ...TimeUsage
    }
  }
`;

<span class="time-usage">
  <ng-container *ngIf="data.timeUsage as timeUsage">{{displayTimeUsage(timeUsage)}}</ng-container>
</span>
