// web-react/src/core/fields/title-field.tsx
import { gql } from '@apollo/client';
import React from 'react';
import { TitleFieldFragment } from '../../generated/graphql-types';
import { FragmentProps } from '../../util/fragment-props';
import { Text, textFragment } from '../text';

export function TitleField({ data }: FragmentProps<TitleFieldFragment>) {
  return <Text data={data.title} />;
}

export const titleFieldFragment = gql`
  fragment TitleField on TitleField {
    title {
      ...Text
    }
  }

  ${textFragment}
`;

// web/src/core/data/title-field.component.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';
import gql from 'graphql-tag';
import { TitleFieldFragment } from '../../generated/graphql-types';
import { textFragment } from '../material/text.pipe';

@Component({
  selector: 'app-title-field',
  templateUrl: './title-field.component.html',
  styleUrls: ['./title-field.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class TitleFieldComponent {
  @Input()
  data!: TitleFieldFragment;
}

export const titleFieldFragment = gql`
  fragment TitleField on TitleField {
    title {
      ...Text
    }
  }

  ${textFragment}
`;

{{ data.title | text }}
