// web/src/core/contest-view-aside.component.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';
import gql from 'graphql-tag';
import { ContestViewAsideFragment } from '../generated/graphql-types';
import { contestViewClockFragment } from './contest-view-clock.component';
import { scoreVariableFragment } from './grading/score-variable.component';
import { textFragment } from './material/text.pipe';

@Component({
  selector: 'app-contest-view-aside',
  templateUrl: './contest-view-aside.component.html',
  styleUrls: ['./contest-view-aside.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class ContestViewAsideComponent {
  @Input()
  data!: ContestViewAsideFragment;
}

export const contestViewAsideFragment = gql`
  fragment ContestViewAside on ContestView {
    problemSetView {
      totalScoreVariable {
        ...ScoreVariable
      }

      assignmentViews {
        assignment {
          problem {
            name
            title {
              ...Text
            }
          }
        }
        totalScoreVariable {
          ...ScoreVariable
        }
      }
    }

    ...ContestViewClock
  }

  ${textFragment}
  ${scoreVariableFragment}
  ${contestViewClockFragment}
`;

<ng-container *ngIf="data.problemSetView! as problemSetView">
  <ng-container *ngIf="problemSetView.totalScoreVariable.value">
    <h2 class="contest-score-title">Score</h2>
    <div class="contest-score">
      <app-grade-variable [data]="problemSetView.totalScoreVariable"></app-grade-variable>
    </div>
  </ng-container>
</ng-container>

<app-contest-view-clock [data]="data"></app-contest-view-clock>

<ng-container *ngIf="data.problemSetView! as problemSetView">
  <h2 class="contest-problem-list-title">Problems</h2>
  <div class="contest-problem-list">
    <ng-container *ngFor="let assignmentView of problemSetView.assignmentViews; index as index">
      <a class="contest-problem-link" [routerLink]="['/problem', assignmentView.assignment.problem.name]"
        [title]="assignmentView.assignment.problem.title | text" routerLinkActive="active">
        {{ assignmentView.assignment.problem.title | text }}
        <span class="contest-problem-score" [appValence]="assignmentView.totalScoreVariable.value?.valence">
          <app-grade-variable [data]="assignmentView.totalScoreVariable"></app-grade-variable>
        </span>
      </a>
    </ng-container>
  </div>
</ng-container>

// web-react/src/core/contest-view-aside.tsx
import { gql } from '@apollo/client';
import React from 'react';
import styled from 'styled-components';
import { ContestViewAsideFragment } from '../generated/graphql-types';
import { ContestViewClock, contestViewClockFragment } from './contest-view-clock';
import { GradeField, scoreFieldFragment } from './grade-field';
import { textFragment } from './text';

// TODO: duplicated?
const AsideHeader = styled.h2`
  text-transform: uppercase;
  font-size: 1.25rem;
  margin: 0 0 0.5rem;
  font-weight: 500;
  line-height: 1.2;
`;

const ContestScore = styled.div`
  white-space: nowrap;
  text-align: right;

  font-size: 2rem;
  margin-bottom: 16px;
`;

const ScoreView = (data: ContestViewAsideFragment) => {
  if (data.problemSetView === null) {
    return null;
  }

  const score = data.problemSetView.totalScoreField.score;

  return (
    <div>
      <AsideHeader>Score</AsideHeader>
      <ContestScore>
        <GradeField data={data.problemSetView.totalScoreField} />
      </ContestScore>
    </div>
  );
}

const ContestProblemList = styled.div`
  padding: 0;
  list-style: none;
`;

const ContestProblemLink = styled.a`
  overflow: hidden;

  margin: 0 -16px;
  padding: 0.5rem 16px;

  display: flex;
  flex-direction: row;

  &:hover {
    text-decoration: none;
  }

  &.active {
    color: #fff;
    background-color: #007bff;
  }
`;

const ContestProblemLinkName = styled.span`
  text-transform: uppercase;

  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
`;

const ContestProblemScore = styled.span`
  margin-left: auto;
`;

export function ContestViewAside({ data }: { data: ContestViewAsideFragment }) {
  if (data.problemSetView === null) {
    return null;
  }

  return (
    <>
      <div>
        <AsideHeader>Score</AsideHeader>
        <ContestScore>
          <GradeField data={data.problemSetView.totalScoreField} />
        </ContestScore>
      </div>

      <ContestViewClock data={data} />

      <AsideHeader>Problems</AsideHeader>
      <ContestProblemList>
        {data.problemSetView.assignmentViews.map((assignmentView, index) => (
          <ContestProblemLink
            key={index}
            // routerLink={['/problem', assignmentView.assignment.problem.name]}
            // routerLinkActive="active"
            title={assignmentView.assignment.problem.title.variant}
          >
            <ContestProblemLinkName>
              {assignmentView.assignment.problem.title.variant}
            </ContestProblemLinkName>
            <ContestProblemScore appValence={assignmentView.totalScoreField.valence}>
              <GradeField data={assignmentView.totalScoreField} />
            </ContestProblemScore>
          </ContestProblemLink>
        ))}
      </ContestProblemList>
    </>
  );
}

export const contestViewAsideFragment = gql`
  fragment ContestViewAside on ContestView {
    problemSetView {
      totalScoreField {
        ...ScoreField
      }

      assignmentViews {
        assignment {
          id
          problem {
            id
            name
            title {
              ...Text
            }
          }
        }
        totalScoreField {
          ...ScoreField
        }
      }
    }

    ...ContestViewClock
  }

  ${textFragment}
  ${scoreFieldFragment}
  ${contestViewClockFragment}
`;
