// web/src/core/contest-problem-assignment-user-tackling-submission-list-modal.component.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';
import gql from 'graphql-tag';
import { ContestProblemAssignmentUserTacklingSubmissionListModalFragment } from '../generated/graphql-types';
import { contestProblemAssignmentUserTacklingSubmissionListFragment } from './contest-problem-assignment-user-tackling-submission-list.component';
import { textFragment } from './material/text.pipe';

@Component({
  selector: 'app-contest-problem-assignment-user-tackling-submission-list-modal',
  templateUrl: './contest-problem-assignment-user-tackling-submission-list-modal.component.html',
  styleUrls: ['./contest-problem-assignment-user-tackling-submission-list-modal.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class ContestProblemAssignmentUserTacklingSubmissionListModalComponent {
  @Input()
  data!: ContestProblemAssignmentUserTacklingSubmissionListModalFragment;

  @Input()
  modal!: NgbActiveModal;
}

export const contestProblemAssignmentUserTacklingSubmissionListModalFragment = gql`
  fragment ContestProblemAssignmentUserTacklingSubmissionListModal on ContestProblemAssignmentUserTackling {
    assignmentView {
      assignment {
        problem {
          title {
            ...Text
          }
        }
      }
    }

    ...ContestProblemAssignmentUserTacklingSubmissionList
  }

  ${textFragment}
  ${contestProblemAssignmentUserTacklingSubmissionListFragment}
`;

<div class="submission-list-dialog-header">
  <h4>
    Submissions for: <strong>{{ data.assignmentView.assignment.problem.title | text }}</strong>
  </h4>
</div>
<div class="submission-list-dialog-body">
  <app-contest-problem-assignment-user-tackling-submission-list [data]="data"></app-contest-problem-assignment-user-tackling-submission-list>
</div>
<div class="submission-list-dialog-footer">
  <button (click)="modal.close()" class="submission-list-dialog-close">Close</button>
</div>

// web-react/src/core/contest-problem-assignment-user-tackling-submission-list-modal.tsx
import { gql } from '@apollo/client';
import { css, cx } from 'emotion';
import React from 'react';
import { ContestProblemAssignmentUserTacklingSubmissionListModalFragment } from '../generated/graphql-types';
import { buttonCss, buttonPrimaryCss } from '../util/components/button';
import { gridCss } from '../util/components/grid';
import { modalFooterCss, modalHeaderCss } from '../util/components/modal';
import { FragmentProps } from '../util/fragment-props';
import {
  ContestProblemAssignmentUserTacklingSubmissionList,
  contestProblemAssignmentUserTacklingSubmissionListFragment,
} from './contest-problem-assignment-user-tackling-submission-list';
import { textFragment } from './text';

export const contestProblemAssignmentUserTacklingSubmissionListModalFragment = gql`
  fragment ContestProblemAssignmentUserTacklingSubmissionListModal on ContestProblemAssignmentUserTackling {
    assignmentView {
      assignment {
        problem {
          title {
            ...Text
          }
        }
      }
    }

    ...ContestProblemAssignmentUserTacklingSubmissionList
  }

  ${textFragment}
  ${contestProblemAssignmentUserTacklingSubmissionListFragment}
`;

export function ContestProblemAssignmentUserTacklingSubmissionListModal({
  data,
}: FragmentProps<ContestProblemAssignmentUserTacklingSubmissionListModalFragment>) {
  return (
    <>
      <div className={modalHeaderCss}>
        <h4>
          Submissions for: <strong>{data.assignmentView.assignment.problem.title.variant}</strong>
        </h4>
      </div>
      <div
        className={cx(
          gridCss,
          css`
            padding: 0;
            max-height: calc(100vh - 260px);
            overflow-y: auto;
          `,
        )}
      >
        <ContestProblemAssignmentUserTacklingSubmissionList data={data} />
      </div>
      <div className={modalFooterCss}>
        <button onClick={() => console.error('TODO')} className={cx(buttonCss, buttonPrimaryCss)}>
          Close
        </button>
      </div>
    </>
  );
}
