// web/src/core/grading/grade-field.component.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';
import gql from 'graphql-tag';
import { GradeFieldFragment } from '../../generated/graphql-types';
import { fulfillmentFieldFragment } from './fulfillment-field.component';
import { scoreFieldFragment } from './score-field.component';

@Component({
  selector: 'app-grade-field',
  templateUrl: './grade-field.component.html',
  styleUrls: ['./grade-field.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class GradingComponent {
  @Input()
  data!: GradeFieldFragment;
}

export const gradeFieldFragment = gql`
  fragment GradeField on GradeField {
    __typename
    ... on FulfillmentField {
      ...FulfillmentField
    }
    ... on ScoreField {
      ...ScoreField
    }
  }

  ${scoreFieldFragment}
  ${fulfillmentFieldFragment}
`;

<ng-container [ngSwitch]="data.__typename">
  <app-score-field *ngSwitchCase="'ScoreField'" [data]="data" [appValence]="data.valence">
  </app-score-field>
  <app-fulfillment-field *ngSwitchCase="'FulfillmentField'" [data]="data" [appValence]="data.valence">
  </app-fulfillment-field>
</ng-container>

// web-react/src/core/grade-field.tsx
import React from 'react';
import styled from 'styled-components';
import { gql } from '@apollo/client';
import { GradeFieldFragment, ScoreFieldFragment, FulfillmentFieldFragment } from '../generated/graphql-types';

export const fulfillmentFieldFragment = gql`
  fragment FulfillmentField on FulfillmentField {
    fulfilled
    valence
  }
`;

export const scoreFieldFragment = gql`
  fragment ScoreField on ScoreField {
    scoreRange {
      max
      allowPartial
      decimalDigits
    }
    score
    valence
  }
`;

export const gradeFieldFragment = gql`
  fragment GradeField on GradeField {
    __typename
    ... on FulfillmentField {
      ...FulfillmentField
    }
    ... on ScoreField {
      ...ScoreField
    }
  }

  ${scoreFieldFragment}
  ${fulfillmentFieldFragment}
`;

const ScoreValue = styled.span`
  font-size: 4rem;
`;

const MaxScoreValue = styled.span`
`;

const ScoreField = (data: ScoreFieldFragment) => {
  return (
    <span>
      {data.score === null ? (
        <MaxScoreValue>
          {'+ '}
          {data.scoreRange.max.toFixed(data.scoreRange.decimalDigits)}
        </MaxScoreValue>
      ) : (
        <>
          <ScoreValue>
            {data.score.toFixed(data.scoreRange.decimalDigits)}
          </ScoreValue>
          <MaxScoreValue>
            {' / '}
            {data.scoreRange.max.toFixed(data.scoreRange.decimalDigits)}
          </MaxScoreValue>
        </>
      )}
    </span>
  );
}

const FulfillmentField = (data: FulfillmentFieldFragment) => {
  switch (data.fulfilled) {
    case null:
      return '+';
    case true:
      return '&#x2713';
    case false:
      return '&#x2717;';
  }
};

export function GradeField({data}: {data: GradeFieldFragment}) {
  switch (data.__typename) {
    case 'ScoreField':
      return ScoreField(data);
    case 'FulfillmentField':
      return FulfillmentField(data);
  }
}
