// web/src/core/login-modal.component.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';
import { Apollo } from 'apollo-angular';
import gql from 'graphql-tag';
import { LoginMutation, LoginMutationVariables } from '../generated/graphql-types';
import { AuthService } from '../util/auth.service';

@Component({
  selector: 'app-login-modal',
  templateUrl: './login-modal.component.html',
  styleUrls: ['./login-modal.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class LoginModalComponent {
  constructor(private readonly apollo: Apollo, private readonly authService: AuthService) {}

  @Input()
  modal!: NgbActiveModal;

  invalidToken = false;

  async logIn(token: string) {
    const { data } = await this.apollo
      .mutate<LoginMutation, LoginMutationVariables>({
        mutation: gql`
          mutation Login($token: String!) {
            logIn(token: $token) {
              user {
                name
                username
              }
              token
            }
          }
        `,
        variables: {
          token,
        },
        fetchPolicy: 'no-cache',
      })
      .toPromise();

    if (data === null || data === undefined) {
      throw Error('error during login');
    }

    if (data.logIn === null) {
      this.invalidToken = true;

      return;
    }

    await this.authService.setAuth(data.logIn);

    this.modal.close();
  }
}

<form class="login-form" (ngSubmit)="$event.preventDefault(); logIn($event.target.elements.token.value)">
  <div class="login-dialog-body">
    <label class="login-token-label" for="token">Token</label>
    <input class="login-token-input" id="token" name="token" type="password" [class.is-invalid]="invalidToken" />
    <small class="login-token-suggestion" [hidden]="invalidToken">
      Insert the token or password provided to you. No username needed.
    </small>
    <small class="login-token-invalid">
      Invalid token.
    </small>
  </div>
  <div class="login-dialog-footer">
    <button (click)="modal.dismiss()" class="login-dialog-cancel" type="button">Cancel</button>
    <button class="login-dialog-submit" type="submit">Log in</button>
  </div>
</form>

// web-react/src/core/login-modal.tsx
import { gql, useMutation } from '@apollo/client';
import React, { useState } from 'react';
import { LoginMutation, LoginMutationVariables } from '../generated/graphql-types';
import { Modal } from '../util/components/modal';

export function LoginModal({ show, onClose }: { show: boolean; onClose: () => void }) {
  const [invalidToken, setInvalidToken] = useState(false);
  const [token, setToken] = useState('');
  const [logIn] = useMutation<LoginMutation, LoginMutationVariables>(gql`
    mutation Login($token: String!) {
      logIn(token: $token) {
        user {
          id
          name
          username
        }
        token
      }
    }
  `);

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    const { data } = await logIn({
      variables: {
        token,
      },
      fetchPolicy: 'no-cache',
    });

    if (data === null || data === undefined) {
      throw Error('error during login');
    }

    if (data.logIn === null) {
      setInvalidToken(true);

      return;
    }

    // await this.authService.setAuth(data.logIn);

    onClose();
  };

  return (
    <Modal show={show} onClose={onClose}>
      <form onSubmit={handleSubmit}>
        <div>
          <label htmlFor="token">Token</label>
          <input
            className="login-token-input"
            id="token"
            name="token"
            type="password"
            value={token}
            onChange={e => {
              setToken(e.target.value);
            }}
          />
          <small className="login-token-suggestion" hidden={invalidToken}>
            Insert the token or password provided to you. No username needed.
          </small>
          <small className="login-token-invalid" hidden={!invalidToken}>
            Invalid token.
          </small>
        </div>
        <div className="login-dialog-footer">
          <button className="login-dialog-cancel" type="button" onClick={onClose}>
            Cancel
          </button>
          <button className="login-dialog-submit" type="submit">
            Log in
          </button>
        </div>
      </form>
    </Modal>
  );
}
